server:
  port: 8082
  session:
    timeout: 300
spring:
    datasource:
        name: test
        url: jdbc:mysql://47.94.151.130:3306/job?useUnicode=true&characterEncoding=utf-8
        username: root
        password: root
#        url: jdbc:mysql://123.206.49.113:3306/job?useUnicode=true&characterEncoding=utf-8
#        username: root
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    http:
      multipart:
        max-file-size: 5Mb
#邮箱配置
    mail:
       host: smtp.163.com
       username: 15765539672@163.com
       password: 1769105723jhn
       port: 25
       default-encoding: UTF-8
       protocol: smtp
       properties:
         mail:
           smth:
             auth: true
             starttls:
               enable: true
               required: true

